branch-defaults:
  default:
    environment: udacity-c2-basic-server-dev
    group_suffix: null
global:
  application_name: udacity-c2-basic-server
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
